"""Add detailed vehicle specs to Estimate model

Revision ID: bc5c6503d712
Revises: 81fa95958fa3
Create Date: 2026-07-15 11:49:51.541355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc5c6503d712'
down_revision = '81fa95958fa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estimates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('km_driven', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('seller_type', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('owner', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('mileage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('engine', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_power', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('seats', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estimates', schema=None) as batch_op:
        batch_op.drop_column('seats')
        batch_op.drop_column('max_power')
        batch_op.drop_column('engine')
        batch_op.drop_column('mileage')
        batch_op.drop_column('owner')
        batch_op.drop_column('seller_type')
        batch_op.drop_column('km_driven')

    # ### end Alembic commands ###
